apiVersion: apps/v1
kind: Deployment
metadata:
  name: myfirstpoddeploy
  labels:
    app: node
spec:
  template:
    metadata:
      name: myfirstpod
      labels:
        app: node
    spec:
      containers:
        - name: myfirstpod
          image: psrv3/todoapp
  replicas: 3
  selector:
    matchLabels:
      app: node
